---

name: Build and push docker image to Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        run: |
          git rev-parse --short HEAD

      - name: Push docker image
        run: |
          echo "blah"
