---

name: Build and push docker image to Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Build docker image
      #   run: |
      #     docker image build -t "ambimax/ansible-playbook-runner:develop-$(git rev-parse --short HEAD)" .

      - name: Push docker image
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker image tag ambimax/ansible-playbook-runner:develop-$(git rev-parse --short HEAD) ambimax/ansible-playbook-runner
          docker image push ambimax/ansible-playbook-runner